### ISSUE TITLE
Is airnotifier still needed?

### ISSUE THREAD

**Issue by manohar-voggu** [NinjasCL-labs/airnotifier-moodle-plugin-firebase-api#2]
After going through the README and having a quick glance at the code, I was left with a slight doubt if airnotifier is needed to be running along with this project for it to work.

@clsource can you please confirm that airnotifier is not needed  and this is a complete replacement :)

**Comment by clsource** [comment]
this is a complete replacement. Airnotifier is not needed 👍 
(But you need to update your clients to change AirNotifier tokens to Firebase tokens)
