### ISSUE TITLE
'database' parameter in config

### ISSUE THREAD

**Issue by manohar-voggu** [NinjasCL-labs/airnotifier-moodle-plugin-firebase-api#3]
Coming from airnotifier, I know mongodb database is used to store airnotifier's data and a url to the mongodb database needs to be specified in airnotifer config file.

But I couldn't understand what 'database' parameter in this project's config does. Can I put-in link to mongodb running on my local machine? @clsource please hint me on the 'database' parameter...

https://github.com/NinjasCL-labs/airnotifier-moodle-plugin-firebase-api/blob/2153732f167fedc527cf5f9bac1ade3f541027a0/index.js#L45-L50

**Comment by clsource** [comment]
It's the common database config for Firebase https://firebase.google.com/docs
This is a solution that works with Firebase only. Air notifier is not needed 👍
