### ISSUE TITLE
Parsing moodle request's body: token is null

### ISSUE THREAD

**Issue by manohar-voggu** [NinjasCL-labs/airnotifier-moodle-plugin-firebase-api#4]
When a request was sent by moodle's airnotifier plugin:
https://github.com/NinjasCL-labs/airnotifier-moodle-plugin-firebase-api/blob/2153732f167fedc527cf5f9bac1ade3f541027a0/index.js#L140-L144
After this code, I did console.log(device, token, extra) , I got "undefined" for all three of them. 
I have checked that console.log(request.body) contains all 3 values. But doing a request.body.token gives an "undefined"

When I sent a POST request with x-www-form-urlencoded body using Postman(as described in README),I got the correct values from the console.log(), not "undefined".

@clsource hence I doubt if our assumption that moodle request being x-www-form-urlencoded is not true
https://github.com/NinjasCL-labs/airnotifier-moodle-plugin-firebase-api/blob/2153732f167fedc527cf5f9bac1ade3f541027a0/index.js#L62-L63

**Comment by manohar-voggu** [comment]
Let me correct myself. I'm not sure if the problem is with moodle request body not being x-www-form-urlencoded. Because the request has `'content-type': 'application/x-www-form-urlencoded'` header.

What I am sure is `req.body.value` fails and is "undefined". This causes an error `'Exactly one of topic, token or condition is required'` as token is not available..

**Comment by clsource** [comment]
Please, it would be handy to have some logs to determine the request object.
It would be possible that is sending it as string, hence it would be undefined if fetched as object.

Maybe  `const { device, token, extra } = body`; 

can be replaced by something like.

```js
 const { device, token, extra } = (typeof body === "string" || body instanceof String ? JSON.parse(body) : body); 
```

**Comment by manohar-voggu** [comment]
Sorry about that, here is the [log file](https://gist.github.com/manohar-voggu/0e3b4842941f45b81cc9ebd5d553907a)
It's the output from terminal upon error.

After the line `const { device, token, extra } = body;`,
I added:
```
console.log('request: ', request);
server.log.info('device: ',device);
server.log.info('token: ',token);
server.log.info('extra: ',extra);
```

**Comment by clsource** [comment]
That logs show something weird

```js
 body: {
    '{"device":"Android","token":"czC2Qd0jKQY:APA91bHVabL8V-HW0HtiRnUV6rZE26uDQdpTacZEiH4glXqhtz0RVOPMx1DVdC_VLxSF1hCjiYc5Ob5UrkgchqDijUcE7ITuoQoGo9GMrjuvkbxe_H-frIGCrpaNNlLDMhaYbhSpqJIf","extra":{"title":"New message from Administrator \\u00a0","text":"hey"}}': ''
  }
```

That means is sending a JS object encoded inside a string.

Please could you do a console.log of the `request.body` object so we can determine how that body is being parsed?.

```js
 const { body } = request; 
console.log(body);
```

**Comment by manohar-voggu** [comment]
Sorry that's on me. Moodle was sending invalid json, so I edited the file on Moodle's side which is responsible for sending the  POST request so that it sends only a part of the `extra`'s parameter leaving out the invalid json

Will share a separate log with the original moodle's request

About the data type of `body`, `console.log('body type: ', typeof(body))` gave me `body type:  object`

**Comment by manohar-voggu** [comment]
Here is the log file for original request from moodle [log file](https://gist.github.com/manohar-voggu/f2de089475122102170d3a7fbb86be9f). 
I accidentally deleted my moodle server setup and had to reconfigure it. Due to this, please ignore trivial differences like token value etc. between previous log file and this log file

You might notice that `fullmessage` and `customdata ` parameters within `extra` in `request.body` contain invalid json (double quotes within double quotes etc)

This time I included the following:
```
console.log('request: ', request);
server.log.info('device: ',device);
server.log.info('token: ',token);
server.log.info('extra: ',extra);
console.log('body type: ', typeof(body));
console.log('body: ', body);
```

**Comment by clsource** [comment]
It seems that your moodle server is giving wrong formatted json.
I have to make some tricks so it could be parsed.

```js
(() => {
    const body = {
        '{"device":"iOS","token":"ab7b394fd2d8e1cdff5442caf9e931a260231342d3f3fe182a3ba7cf885cd946","extra":{"courseid":1,"modulename":null,"component":"moodle","name":"instantmessage","convid":5,"conversationtype":"1","subject":"New message from user 1","fullmessage":"hey\\n\\n---------------------------------------------------------------------\\nThis is a copy of a message sent to you at \\"Moodle 3.9\\". Go to http:\\/\\/localhost:8888\\/moodle39\\/message\\/index.php?id': '4 to reply.","fullmessageformat":0,"fullmessagehtml":"","smallmessage":"hey","notification":0,"contexturl":null,"contexturlname":null,"replyto":null,"replytoname":null,"savedmessageid":9,"attachment":null,"attachname":null,"timecreated":1593796033,"fullmessagetrust":null,"customdata":"{\\"actionbuttons\\":{\\"send\\":\\"Send\\"},\\"placeholders\\":{\\"send\\":\\"Write a message...\\"},\\"notificationiconurl\\":\\"http:\\\\\\/\\\\\\/localhost:8888\\\\\\/moodle39\\\\\\/theme\\\\\\/image.php\\\\\\/boost\\\\\\/core\\\\\\/1593793742\\\\\\/u\\\\\\/f1\\",\\"courseid\\":1,\\"tokenpluginfile\\":\\"ac05295e219c95e4e76b861f0989163f\\"}","userfromid":"4","userfromfullname":"user 1","usertoid":"2","processor":"moodle","site":"383ecd58915326d70f27e8ef8152af11","date":1593796033,"sitefullname":"Moodle 3.9","siteshortname":"Moodle 3.9","wwwroot":"http:\\/\\/localhost:8888\\/moodle39"}}'
      };

		const key = Object.keys(body)[0];
    const value = body[key];
    const json = JSON.parse(key + value);
    console.log({json});
            
})();
```

**Comment by clsource** [comment]
so how it went @manohar-voggu ? should I close this issue? 👍

**Comment by manohar-voggu** [comment]
@clsource tested the solution just now. Works well😀  . I don't need to modify anything on Moodle's side anymore, thanks to you. Thank you so much for this project in the first place. Closing the issue from my side.

**Comment by sherif4646** [comment]
@clsource please explain what you do to make it work.
Thank you in advanced

**Comment by clsource** [comment]
Please try the latest version since this fix was implemented 👍

**Comment by sherif4646** [comment]
@clsource 
Hello,
i try latest version and when post token from mobile app this error appear,
,\"body\":null,\"error\":{\"name\":\"FastifyError [FST_ERR_CTP_INVALID_MEDIA_TYPE]\",\"code\":\"FST_ERR_CTP_INVALID_MEDIA_TYPE\",\"message\":\"FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: multipart/form-data;
thank you in advanced

**Comment by sherif4646** [comment]
@clsource 
\"content-type\":\"multipart/form-data;

**Comment by clsource** [comment]
try this https://www.fastify.io/docs/latest/ContentTypeParser/

**Comment by sherif4646** [comment]
@clsource thank you very much
the problem was resolved after add this
const Multipart = Symbol('multipart') 
fastify.addContentTypeParser('multipart', (request, done) => {
 request[Multipart] = true
  done()
})
after line
server.register(require("fastify-formbody"));
